name: tea_list
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.12
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_sign_in: ^7.1.1
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.2
  path: ^1.9.1
  permission_handler: ^12.0.1
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#F7A930"
  image_path: "assets/images/icon-256x256_v1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Coiny
      fonts:
        - asset: assets/fonts/Coiny.ttf

flutter_native_splash:
  color: "#f7aa31"
  image: assets/images/icon-256x256_v1.png
  android: true
  ios: true
